# IMEC2001 Herramientas Computacionales 
## Actividad Clase 9: Sistemas de Ecuaciones
### Fecha Límite Entrega (Bloque Neón): <font color="#FF5733">23.59h de Septiembre 6, 2023</font>

Universidad de los Andes — Septiembre 4, 2023.

___
### Tener en Cuenta
La entrega de la **Actividad Clase 9** se puede realizar de dos maneras:
1. Enviar vía Bloque Neón el archivo en Jupyter Notebook (extensión '.ipynb').
2. Enviar vía Bloque Neón el archivo PDF del Jupyter Notebook.

**Nota:** <font color="#FF5733">El nombre del archivo debe ser: `AC9_NombreApellido.ipynb`.</font>

---

## TABLA DE CONTENIDO

### Sección 1: Ejercicios [→](#section1)
1. Ejercicio 1: Ecuaciones Lineales [→](#exercise1)
2. Ejercicio 2: Ecuaciones No Lineales [→](#exercise2)
___

<a id="section1"></a>
# Sección 1: Ejercicios

<a id="exercise1"></a>
## Ejercicio 1: Ecuaciones Lineales

Se tiene el siguiente sistema de ecuaciones lineales:

$$
\begin{cases}
  3x_1 + 2x_2 + x_3 = 1 \\ 
  \\
  2x_1 + 2x_2 + 4x_3 = -2 \\
  \\
  -x_1 + \frac{1}{2}x_2 - x_3 = 0
\end{cases} 
$$

<div class="alert alert-block alert-warning">

1. Utilizando la librería `numpy.linalg.inv` y `numpy.dots`, resuelva el sistema de ecuaciones.
2. Utilizando la librería `numpy.linalg.solve`, resuelva el sistema de ecuaciones.
3. Utilizando la librería `sympy.rref()`, resuelva el sistema de ecuaciones.
4. Utilizando la librería `scipy.optimize.fsolve`, resuelva el sistema de ecuaciones.
5. Utilizando la librería `sympy.solve`, resuelva el sistema de ecuaciones.
    
</div>

In [11]:
# Sistema de Ecuaciones
import numpy as np
from scipy import optimize
import sympy
A = np.array([[3, 2, 1],
            [2, 2, 4],
            [-1, 0.5, -1]])

b = np.array([1, -2, 0])

invA = np.linalg.inv(A)

x = np.dot(invA,b)
x

array([ 0.69230769, -0.15384615, -0.76923077])

In [9]:
# Ítem 2
A = np.array( [[3, 2, 1],
            [2, 2, 4],
            [-1, 0.5, -1]])
b = np.array( [1, -2, 0] )
x = np.linalg.solve(A, b)
x

array([ 0.69230769, -0.15384615, -0.76923077])

In [13]:
# Ítem 3
A_aumentada = sympy.Matrix( [ [3, 2, 1,1],
                            [2, 2, 4,-2],
                            [-1, 0.5, -1,0] ] )
x = A_aumentada.rref()[0]
x

Matrix([
[1, 0, 0,  0.692307692307692],
[0, 1, 0, -0.153846153846154],
[0, 0, 1, -0.769230769230769]])

In [19]:
# Ítem 4
import scipy
def f(z):
    x1 = z[0]
    x2 = z[1]
    x3 = z[2]
    
    F = np.zeros(3)
    
    F[0] = 3 * x1 + 2 * x2 +x3 - 1
    F[1] = 2 * x1 + 2 * x2 + 4 * x3 + 2
    F[2] = -1 * x1 + 0.5 * x2 - x3 
    
    return F

rango = [1,1,1]
x = scipy.optimize.fsolve(func = f, 
                       x0=rango)
x

array([ 0.69230769, -0.15384615, -0.76923077])

In [21]:
# Ítem 5
x1 = sympy.Symbol('x_1')
x2 = sympy.Symbol('x_2')
x3 = sympy.Symbol('x_3')
ec1 = sympy.Eq(3*x1 + 2*x2 + x3, 1) # La derecha de la igualdad va después de la coma
ec2 = sympy.Eq(2*x1 + 2*x2 + 4 * x3, -2)
ec3 = sympy.Eq(-1*x1 + 0.5*x2 + -1 * x3, 0)
sol = sympy.solve([ec1, ec2, ec3], # Lista de ecuaciones
                  [x1, x2, x3]) # Lista de símbolos
sol

{x_1: 0.692307692307692, x_2: -0.153846153846154, x_3: -0.769230769230769}

<a id='exercise2'></a>
## Ejercicio 2: Ecuaciones No Lineales

Se tiene el siguiente sistema de ecuaciones no lineales:

$$
\begin{cases}
  x^2 + y^2 = 1 \\ 
  \\
  xy + yz = -1.1 \\
  \\
  y^2 + z^2 = 2
\end{cases} 
$$

<div class="alert alert-block alert-warning">

1. Utilizando la librería `scipy.optimize.fsolve`, resuelva el sistema de ecuaciones.
1. Utilizando la librería `scipy.optimize.roots`, resuelva el sistema de ecuaciones.
3. Utilizando la librería `sympy.solve`, resuelva el sistema de ecuaciones.
    
</div>

In [31]:
# Ítem 1
import scipy
def f(a):
    x = a[0]
    y = a[1]
    z = a[2]
    F = np.zeros(3)
    
    F[0] = x**2 + y**2 - 1
    F[1] = x * y + y * z + 1.1
    F[2] = y**2  + z**2 - 2
    return F

rango1 = [1,0,0]
rango2 = [0,1,0]
rango3 = [0,0,1]
rx = scipy.optimize.fsolve(func = f, 
                       x0=rango1)
ry = scipy.optimize.fsolve(func = f, 
                       x0=rango2)
rz = scipy.optimize.fsolve(func = f, 
                       x0=rango3)


print(rx,ry,rz)

[1.00000001e+00 2.09774608e-08 1.07677546e+00] [-0.10056089  0.99493091 -1.00504353] [ 0.86413935 -0.5032526   1.32164172]


In [ ]:
# Ítem 2


In [ ]:
# Ítem 3
